import React, { useState, useEffect, useRef } from 'react';

// Declare the Pyodide global object for TypeScript
declare global {
  interface Window {
    loadPyodide: (config?: { indexURL?: string }) => Promise<any>;
    pyodide: any;
  }
}

const App: React.FC = () => {
  const [pyodide, setPyodide] = useState<any>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [plotSrc, setPlotSrc] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [statusMessage, setStatusMessage] = useState<string>("Initializing Pyodide...");

  // Ref to ensure useEffect runs only once for Pyodide initialization
  const pyodideLoadedRef = useRef(false);

  useEffect(() => {
    if (pyodideLoadedRef.current) return; // Prevent re-running
    pyodideLoadedRef.current = true;

    const loadAndRunPyodide = async () => {
      try {
        // 1. Load Pyodide
        // Check if Pyodide script is already loaded
        if (!document.getElementById('pyodide-script')) {
          const script = document.createElement('script');
          script.id = 'pyodide-script';
          script.src = 'https://cdn.jsdelivr.net/pyodide/v0.25.1/full/pyodide.js';
          script.async = true;
          document.head.appendChild(script);

          await new Promise<void>((resolve, reject) => {
            script.onload = () => resolve();
            script.onerror = () => {
              setStatusMessage("Failed to load Pyodide script.");
              setError("Failed to load Pyodide script.");
              reject(new Error("Failed to load Pyodide script."));
            };
          });
        }
        
        // Pyodide script loaded, proceed with loading Pyodide directly.


        const pyodideInstance = await window.loadPyodide({
          // indexURL: "https://cdn.jsdelivr.net/pyodide/v0.25.1/full/" // Optional: specify indexURL
        });
        setPyodide(pyodideInstance);
        setStatusMessage("Pyodide loaded. Loading Matplotlib...");

        // 2. Load Python packages (Matplotlib)
        await pyodideInstance.loadPackage('matplotlib');
        setStatusMessage("Matplotlib loaded. Generating plot...");

        // 3. Define the Python script
        const pythonScript = `
import matplotlib
matplotlib.use('Agg') # Use non-interactive backend
import matplotlib.pyplot as plt
import io
import base64

# Dummy data
x_data = [1, 2, 3, 4, 5]
y_data = [10, 8, 12, 7, 11]

fig, ax = plt.subplots(figsize=(6, 4)) # Define figure size
ax.plot(x_data, y_data, marker='o', linestyle='-', color='skyblue')
ax.set_title("Simple Plot from Python", fontsize=14)
ax.set_xlabel("X Values", fontsize=12)
ax.set_ylabel("Y Values", fontsize=12)
ax.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout() # Adjust layout to prevent labels from being cut off

# Save plot to a BytesIO buffer
buf = io.BytesIO()
fig.savefig(buf, format='png', dpi=100) # Specify DPI for clarity
buf.seek(0)

# Encode to base64
img_base64 = base64.b64encode(buf.read()).decode('utf-8')
buf.close()

img_base64 # This will be the return value
        `;

        // 4. Run the Python script
        const result = await pyodideInstance.runPythonAsync(pythonScript);
        setPlotSrc(`data:image/png;base64,${result}`);
        setStatusMessage("Plot generated successfully!");
        setError(null);

      } catch (err: any) {
        console.error("Pyodide initialization or script execution error:", err);
        setError(`Error: ${err.message || 'An unknown error occurred.'}`);
        setStatusMessage("An error occurred.");
      } finally {
        setIsLoading(false);
      }
    };

    loadAndRunPyodide();

  }, []); // Empty dependency array ensures this runs once on mount

  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center justify-center p-4 font-sans">
      <div className="bg-white p-6 md:p-8 rounded-xl shadow-2xl w-full max-w-2xl text-center">
        <header className="mb-6">
          <h1 className="text-3xl font-bold text-indigo-600">Pyodide React Visualizer</h1>
          <p className="text-gray-600 mt-2">
            Displaying a Matplotlib plot generated by a Python script running in the browser via Pyodide.
          </p>
        </header>

        {isLoading && (
          <div className="my-8 p-4 border border-blue-300 bg-blue-50 rounded-lg">
            <div className="flex items-center justify-center space-x-2">
              <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-indigo-500"></div>
              <p className="text-indigo-700">{statusMessage}</p>
            </div>
          </div>
        )}

        {error && !isLoading && (
          <div className="my-8 p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg">
            <p className="font-semibold">Error:</p>
            <p>{error}</p>
            <p className="mt-2 text-sm">Please check the console for more details. Ensure you have an internet connection for Pyodide to load.</p>
          </div>
        )}

        {!isLoading && plotSrc && !error && (
          <div className="my-8 border border-gray-300 rounded-lg overflow-hidden shadow-md">
            <h2 className="text-xl font-semibold text-gray-700 p-3 bg-gray-50 border-b border-gray-300">
              Generated Plot:
            </h2>
            <img 
              src={plotSrc} 
              alt="Matplotlib plot generated by Pyodide" 
              className="w-full h-auto"
            />
          </div>
        )}
         {!isLoading && !plotSrc && !error && (
            <div className="my-8 p-4 bg-yellow-50 border border-yellow-300 text-yellow-700 rounded-lg">
                <p>Plot could not be generated. Please check the console for errors.</p>
            </div>
        )}
      </div>
      <footer className="mt-8 text-center text-gray-500 text-sm">
        <p>Powered by Pyodide, React, and Matplotlib.</p>
      </footer>
    </div>
  );
};

export default App;
